version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.4
    commands:
      - composer install
  build:
    commands:
      - zip -r app.zip . -x "*.git*" "tests/*" "scripts/*"
  post_build:
    commands:
      - aws s3 cp app.zip s3://devops-carrental-bucket/car-build/app.zip
artifacts:
  files:
    - app.zip
