branch-defaults:
  default:
    environment: MyNewEnv-envA
    group_suffix: null
global:
  application_name: MyNewEnv
  default_region: ap-southeast-2
  profile: null
  platform_name: PHP
  platform_version: 8.4.al2023
  workspace_type: Application
